### ISSUE TITLE
Preview not working on macOS Anki 2.1.56

### ISSUE THREAD

**Issue by dshai** [rad4day/anki-editor-preview-plugin#11]
Hi, this addon stopped working for me when I upgraded from Anki 2.1.48 -> 2.1.56.

On add card window, the preview area just shows a black box:
<img width="720" alt="Add_window" src="https://user-images.githubusercontent.com/53975368/212036151-87c67c4f-6c25-45d8-a1a1-8f095ae02845.png">

However after the card is created, the preview renders properly in the browse window:
<img width="1552" alt="Browse_window" src="https://user-images.githubusercontent.com/53975368/212036351-cd00ff78-4eed-4ae2-bacf-59b6e3d6ec54.png">

I am using Anki 2.1.56 Qt6 on macOS, and I see the same behavior with Intel and Apple silicon Anki builds.  Here is the full About Anki window:
<img width="912" alt="About anki" src="https://user-images.githubusercontent.com/53975368/212036520-fffe9e24-f9a8-48e2-8f89-2ed2759d5f9e.png">

**Comment by niposch** [comment]
This might not be related to the live preview plugin. I had the same issue on windows 11 and resolved it by disabling the "Searching, PDF Reading & Note-Taking in Add Dialog" Plugin =>  https://ankiweb.net/shared/info/1781298089 . After I disabled this plugin, I restarted anki and it is working as expected.
