### ISSUE TITLE
requesting a feature: side pane or external window

### ISSUE THREAD

**Issue by Hosseingsd** [rad4day/anki-editor-preview-plugin#12]
I need this addon to display NOT on the bottom but on the side (or if it's not possible in an external window. Please update your addon to have the option to be displayed on the side/button. 

I show you an addon that already has this feature to show you what I mean. 
example addon is "[Browser: Table/Editor side-by-side (horizontal split)](https://ankiweb.net/shared/info/831846358)"

![1](https://user-images.githubusercontent.com/110593678/227535927-56a4fbbb-63d2-43da-8236-0c3dbf9cf392.png)
![2](https://user-images.githubusercontent.com/110593678/227536216-d0196f4a-f3af-4907-bf28-dea571afe520.png)
![3](https://user-images.githubusercontent.com/110593678/227536075-18c032f1-0a08-44df-972f-16b19f63b1f1.png)

**Comment by rad4day** [comment]
Thank you for messaging me about this again, just wanted to check that this is indeed what you envisioned:

![image](https://user-images.githubusercontent.com/12465878/227573748-f2ec03e5-8ff4-4f90-9f94-c95b0f0a8bd2.png)

I'm currently testing a build which lets you configure the location between above, below, left and right of the editor.

**Comment by rad4day** [comment]
I'll also fix the weighting of the splitting at the same time. Might make for some weird splits after installing the Update as 4:1 was quite the high default factor (:

**Comment by Hosseingsd** [comment]
Thank you very much.

**Comment by rad4day** [comment]
Should be resolved by 8e2815b

Changes are live on Ankiweb.

**Comment by Hosseingsd** [comment]
> Thank you for messaging me about this again, just wanted to check that this is indeed what you envisioned:
> 
> ![image](https://user-images.githubusercontent.com/12465878/227573748-f2ec03e5-8ff4-4f90-9f94-c95b0f0a8bd2.png)
> 
> I'm currently testing a build which lets you configure the location between above, below, left and right of the editor.


Yes! and thank you very much! this update is even more useful in **add note** and **edit** windows

**Comment by Hosseingsd** [comment]
> Thank you for messaging me about this again, just wanted to check that this is indeed what you envisioned:

Yes! and thank you very much! this update is even more useful in add note and edit windows

**Comment by Hosseingsd** [comment]
> I'll also fix the weighting of the splitting at the same time. Might make for some weird splits after installing the Update as 4:1 was quite the high default factor (:

splitting is easy to change with just clicking and dragging <kbd>...</kbd>
