### ISSUE TITLE
What means this phrase in the addon's description?

### ISSUE THREAD

**Issue by Rodvi** [rad4day/anki-editor-preview-plugin#25]
In the description of your addon on AnkiWeb you wrote:

> It was written out of pure annoyance of having to open the “Cards…” screen every time.

I am confused why did you write `the “Cards…” screen` here? I think you should write `the “Preview” screen` instead - this will help new users to better understand the true purpose of your addon. Please correct me if I am wrong (explain how your addon can help with `the “Cards…” screen`).

**Comment by rad4day** [comment]
The Add Cards UI still seems to not have a preview screen, which was the UI that originally made me want this feature.

A workaround for this was (or still is) to click the “Cards…” button before saving the Card to see if you mistyped your math equations.

**Comment by Rodvi** [comment]
Oh, now I see. Thanks for the explanation.
