### ISSUE TITLE
Feature request for side-by-side view of editor and preview

### ISSUE THREAD

**Issue by talenelat-elin** [rad4day/anki-editor-preview-plugin#4]
If it's not too inconvenient, could you add an option for displaying the preview to one side of the editor fields in the add window. or even paste a code snippet for me to change in the main .py file

**Comment by nickdvlpr** [comment]
I haven't tried it myself, but in theory you could:
1. Change Line 47 in the code to: `split.setOrientation(Qt.Horizontal)`
2. Use one more add-on: https://ankiweb.net/shared/info/831846358

Let me know if this works!

**Comment by talenelat-elin** [comment]
The code change does work and was all I needed, thanks!
