### ISSUE TITLE
Preview not working for ⁨2.1.54

### ISSUE THREAD

**Issue by lkyhfx** [rad4day/anki-editor-preview-plugin#8]
Preview is not showing in anki 2.1.54

**Comment by rad4day** [comment]
Thank you for your report :D

Can you provide me with some additional information?
It seems to be working with 2.1.55 for me.

Can you confirm that the plugin is in fact enabled in the plugin manager and that you restarted Anki once after installing?
If so, please send me the version numbers from the Help>About screen. So I can set up a test environment to confirm this.

Also, are you on Windows, macOS, or Linux?

Those are my currently working ones:
![image](https://user-images.githubusercontent.com/12465878/200562541-53ab1af3-a50e-4a59-b9c9-b7e1f3882874.png)

**Comment by lkyhfx** [comment]
I am using Windows 11, and anki is restarted after installing the plugin. Preview is not showing after clicking the preview button multiple times.
<img width="565" alt="屏幕截图 2022-11-09 085700" src="https://user-images.githubusercontent.com/30225731/200710184-1ec4ccfe-0887-48cb-8051-1236758eca13.png">
<img width="602" alt="屏幕截图 2022-11-09 085726" src="https://user-images.githubusercontent.com/30225731/200710200-6112b0bb-57f8-4898-8e26-8b4e5629201c.png">
<img width="476" alt="屏幕截图 2022-11-09 090007" src="https://user-images.githubusercontent.com/30225731/200710207-fcb28201-a476-40da-b790-0b71338a5711.png">

**Comment by rad4day** [comment]
I have tried to reproduce this again today. I am not able to reproduce. :/
